### ISSUE TITLE
HCI? 

### ISSUE THREAD

**Issue by professor** [software-patterns/hci-language#3]
HCI has a very well understood meaning, Human-computer interaction which entails user-centered design. We may need a different repo name.

**Comment by kejadlen** [comment]
I have the same thought every time this repo's name shows up in my email. 😅

**Comment by benchristel** [comment]
I agree. What's a name that implies "human centered" while encompassing code and other non-user-facing activities of software development?

**Comment by benchristel** [comment]
Perhaps it's too early to name the repo after its content, since we don't yet know what it's going to turn into. We don't even know if we want to keep the pattern language format.

I'm going to change the name to "workshop", which I think has the right connotation of being a perpetual WIP. It also implies a process—that of workshopping each other's writing—without being specific about content.
